### ISSUE TITLE
Improvement SMIT-Chat-App

### ISSUE THREAD

**Issue by ahmedrazabaloch** [ghousahmed/smit-chat-app#1]

**Comment by Muhammadahmed2001** [comment]
i will upload profile image.if user want to add pic so he can add otherwise show the alphabetic picture.

**Comment by usman-rizwan** [comment]
Hi everyone,

I noticed that there seems to be an issue with the safe route in the Chat app. After some investigation, I believe I have identified the problem and am willing to work on fixing it.

Looking forward to contributing to the improvement of the Smit Chat app!

Best regards,
usman-rizwan

**Comment by ahmedrazabaloch** [comment]
> Hi everyone,
> 
> I noticed that there seems to be an issue with the safe route in the Chat app. After some investigation, I believe I have identified the problem and am willing to work on fixing it.
> 
> Looking forward to contributing to the improvement of the Smit Chat app!
> 
> Best regards, usman-rizwan

@usman-rizwan ok usman do it

**Comment by ahmedrazabaloch** [comment]
> i will upload profile image.if user want to add pic so he can add otherwise show the alphabetic picture.

@Muhammadahmed2001 ok ahmed best of luck 👍
